#!/usr/bin/env bash
# Get directory of this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Remove all running docker containers
docker compose -f "$DIR/compose/coverage.yml" --project-directory "$DIR/.." --project-name=squirrel_coverage down --volumes --remove-orphans

# Run tests with coverage report
docker compose -f "$DIR/compose/coverage.yml" --project-directory "$DIR/.." --project-name=squirrel_coverage up --abort-on-container-exit --exit-code-from=coverage coverage

# Remove all running docker containers
docker compose -f "$DIR/compose/coverage.yml" --project-directory "$DIR/.." --project-name=squirrel_coverage down --volumes --remove-orphans